services:
  mongo:
    image: mongo:6
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: todo-server
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/todo-app
      - TOKEN_KEY=devsecret
      - PORT=${SERVER_PORT:-8080}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build: ./client
    container_name: todo-client
    ports:
      - "${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}"
    environment:
      # Helps CRA detect file changes on mounted volumes (Mac/WSL)
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=${CLIENT_PORT:-3000}
      # Point the client to the local API when running via Docker
      - REACT_APP_API_BASE_URL=http://localhost:${SERVER_PORT:-8080}/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data:
